<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUPCmNOk\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUPCmNOk/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUPCmNOk.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUPCmNOk\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerUPCmNOk\App_KernelDevDebugContainer([
    'container.build_hash' => 'UPCmNOk',
    'container.build_id' => 'b98c9fbc',
    'container.build_time' => 1638748550,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUPCmNOk');
