<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHyPA4t3\App_KernelDevContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHyPA4t3/App_KernelDevContainer.php') {
    touch(__DIR__.'/ContainerHyPA4t3.legacy');

    return;
}

if (!\class_exists(App_KernelDevContainer::class, false)) {
    \class_alias(\ContainerHyPA4t3\App_KernelDevContainer::class, App_KernelDevContainer::class, false);
}

return new \ContainerHyPA4t3\App_KernelDevContainer([
    'container.build_hash' => 'HyPA4t3',
    'container.build_id' => 'ee84cddc',
    'container.build_time' => 1638748533,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHyPA4t3');
